
### d - dimensional Gaussian generated by 1 - dimensional latent factors -  let d be EVEN!
## m : Number of rows of matrix
## n : Number of columnes of matrix
## d : dimension of data


# MCAR missing pattern
gendata3 = function(m, n, N, d, seed){
  # Generate Mean latent factors
  set.seed(seed)
  row1 = runif(m, -1, 1)
  col1 = rnorm(n, 0, 1)
  # Generate Covariance latent factors
  row2 = runif(m, 0.2, 1)
  col2 = abs(rnorm(n, 0, 1))
  
  Data = matrix(0, m*n, N*d)
  
  for(i in c(1:m)){
    for(j in c(1:n)){
      if(d == 1){
        mij = (row1[i]*col1[j]) 
        vij = (row2[i]*col2[j]) 
        if(i == 1 & j == 1){ # Data is tailored to the case where A(1, 1) is target!
          target_mean = mij
          target_cov = (vij)
        }
        Data[(i-1)*n + j, ] = rnorm(N, mij, sqrt(vij))
      }else if(d > 1){
        mij = (row1[i]*col1[j]) * rep(c(1, -1), (d/2))
        vij = (row2[i]*col2[j]) * rep(c(1, 1/2), (d/2))
        if(i == 1 & j == 1){ # Data is tailored to the case where A(1, 1) is target!
          target_mean = mij
          target_cov = (vij)
        }
        Data[(i-1)*n + j, ] = c(t(rmvnorm(N, mij, diag(vij)))) 
      }
    }
  }
  
  Masking = matrix(rbinom(m*n, 1, 0.7), m, n)
  
  lst = list(Data = Data, Masking = Masking, target_mean = target_mean, target_cov = target_cov)
  
  return(lst)
}

# L-shape missing pattern
gendata4 = function(m, n, N, d, e_T, e_N, seed){
  
  set.seed(seed)
  row1 = runif(m, -1, 1)
  col1 = rnorm(n, 0, 1)
  
  row2 = runif(m, 0.2, 1)
  col2 = abs(rnorm(n, 0, 1))
  
  Data = matrix(0, m*n, N*d)
  
  for(i in c(1:m)){
    for(j in c(1:n)){
      if(d == 1){
        mij = (row1[i]*col1[j]) 
        vij = (row2[i]*col2[j]) 
        if(i == 1 & j == 1){ # Data is tailored to the case where A(1, 1) is target!
          target_mean = mij
          target_cov = (vij)
        }
        Data[(i-1)*n + j, ] = rnorm(N, mij, sqrt(vij))
      }else if(d > 1){
        mij = (row1[i]*col1[j]) * rep(c(1, -1), (d/2))
        vij = (row2[i]*col2[j]) * rep(c(1, 1/2), (d/2))
        if(i == 1 & j == 1){ # Data is tailored to the case where A(1, 1) is target!
          target_mean = mij
          target_cov = (vij)
        }
        Data[(i-1)*n + j, ] = c(t(rmvnorm(N, mij, diag(vij)))) 
      }
    }
  }
  
  row_zero = floor(m^{e_T})
  col_zero = floor(n^{e_N})
  
  zero_mat = matrix(0, row_zero, col_zero)
  one_mat1 = matrix(1, row_zero, (n - col_zero))
  one_mat2 = matrix(1, (m - row_zero), col_zero)
  one_mat3 = matrix(1, (m - row_zero), (n - col_zero))
  
  Masking = rbind(cbind(zero_mat, one_mat1), cbind(one_mat2, one_mat3))
  
  lst = list(Data = Data, Masking = Masking, target_mean = target_mean, target_cov = target_cov)
  
  return(lst)
  
  
}

# L-shape + Confounding missing pattern

gendata5 = function(m, n, N, d, e_T, e_N, seed){
  
  set.seed(seed)
  row1 = runif(m, -1, 1)
  col1 = rnorm(n, 0, 1)
  
  row2 = runif(m, 0.2, 1)
  col2 = abs(rnorm(n, 0, 1))
  
  Data = matrix(0, m*n, N*d)
  
  for(i in c(1:m)){
    for(j in c(1:n)){
      if(d == 1){
        mij = (row1[i]*col1[j]) 
        vij = (row2[i]*col2[j]) 
        if(i == 1 & j == 1){ # Data is tailored to the case where A(1, 1) is target!
          target_mean = mij
          target_cov = (vij)
        }
        Data[(i-1)*n + j, ] = rnorm(N, mij, sqrt(vij))
      }else if(d > 1){
        mij = (row1[i]*col1[j]) * rep(c(1, -1), (d/2))
        vij = (row2[i]*col2[j]) * rep(c(1, 1/2), (d/2))
        if(i == 1 & j == 1){ # Data is tailored to the case where A(1, 1) is target!
          target_mean = mij
          target_cov = (vij)
        }
        Data[(i-1)*n + j, ] = c(t(rmvnorm(N, mij, diag(vij)))) 
      }
    }
  }
  expit = function(x) 1/(1 + exp(-x))
  row_prob = expit((row1^2)/2 + row2/2)
  
  Masking = matrix(0, m, n)
  for(i in c(1:m)){
    Masking[i, ] = rbinom(n, 1, row_prob[i])
  }
  
  row_zero = floor(m^{e_T})
  col_zero = floor(n^{e_N})
  
  Masking[c(1:row_zero), c(1:col_zero)] = 0
  
  lst = list(Data = Data, Masking = Masking, target_mean = target_mean, target_cov = target_cov)
  
  return(lst)
  
}





